### ISSUE TITLE
A list of pairs that should not be converted in v2t

### ISSUE THREAD

**Issue by sudoghut** [yukiyuqichen/CHAR#1]
Here is a list of pairs that should not be converted in v2t:

珪圭

敦惇

勛勳

傳傅

炅炔

餐飧

楠柟

沉沈

敦惇

**Comment by yukiyuqichen** [comment]
Errors have been corrected.

**Comment by yukiyuqichen** [comment]
Errors have been corrected

**Comment by sudoghut** [comment]
These changes haven't been applied to the python package

**Comment by yukiyuqichen** [comment]
> These changes haven't been applied to the python package

Sorry for the mistake. The python package has been updated now.
