### ISSUE TITLE
Applying the update to the python package

### ISSUE THREAD

**Issue by sudoghut** [yukiyuqichen/CHAR#8]
I received a report that someone encountered a conversion error that we had fixed months ago.

What would be the best solution for our Python users to update the char package? Running

```
pip install char-converter -U
```

regularly?

**Comment by yukiyuqichen** [comment]
> I received a report that someone encountered a conversion error that we had fixed months ago.
> 
> What would be the best solution for our Python users to update the char package? Running
> 
> ```
> pip install char-converter -U
> ```
> 
> regularly?

Sorry for the mistake! The python package has been updated now. The correct command to update the package is: "pip install char_converter -U". Please notice that there is a "_" in the package name, instead of a "-".
